# Generated by Django 2.2.5 on 2021-02-20 12:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Position',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='employee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fullname', models.CharField(max_length=20)),
                ('emp_code', models.CharField(max_length=40)),
                ('mobile_no', models.CharField(max_length=20)),
                ('position', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='employee_reg.Position')),
            ],
        ),
    ]
